# Generated by Django 5.2.7 on 2025-10-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('instrumento', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('factor8', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'CALIFICACION',
            },
        ),
    ]
